name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *' # roda a cada hora
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate stats
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN_STATS }}" \
          "https://github-readme-stats.vercel.app/api?username=OliMatheuss&show_icons=true&theme=tokyonight" \
          -o stats.svg

      - name: Commit updated stats
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add stats.svg
          git commit -m "Update GitHub Stats" || echo "No changes"
          git push
